version: '3.8'

services:
  # Nginx Yük Dengeleyici
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - mynetwork

  # İlk Spring Boot Uygulaması
  app1:
    build: .
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=dagitik
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - mynetwork

  # İkinci Spring Boot Uygulaması (Replikasyon)
  app2:
    build: .
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=dagitik
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - mynetwork

  # PostgreSQL Veritabanı
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=dagitik
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  # Redis Cache
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

volumes:
  postgres_data:
  redis_data:

networks:
  mynetwork:
